apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-apps-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 
    targetRevision: main
    path: apps/argo-test-apps
    helm:
      valueFiles:
        - values/dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-test-apps-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
